import { FiltersProvider } from '@/context/filters'
import './globals.css'
import { Inter } from 'next/font/google'
import { CartProvider } from '@/context/cart'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Market Place',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <CartProvider>
        <FiltersProvider>
          <body className={inter.className}>{children}</body>
        </FiltersProvider>
      </CartProvider>
    </html>
  )
}
